// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

    static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyAnKsE4cLaMFNaSEV7LVWx2JT_kaC4Uoyk",
    authDomain: "chatflutter-181be.firebaseapp.com",
    databaseURL: "https://chatflutter-181be-default-rtdb.firebaseio.com",
    projectId: "chatflutter-181be",
    storageBucket: "chatflutter-181be.appspot.com",
    messagingSenderId: "867280179629",
    appId: "1:867280179629:web:8da4f34a533b80339ed124",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAnKsE4cLaMFNaSEV7LVWx2JT_kaC4Uoyk",
    authDomain: "chatflutter-181be.firebaseapp.com",
    databaseURL: "https://chatflutter-181be-default-rtdb.firebaseio.com",
    projectId: "chatflutter-181be",
    storageBucket: "chatflutter-181be.appspot.com",
    messagingSenderId: "867280179629",
    appId: "1:867280179629:web:8da4f34a533b80339ed124"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAnKsE4cLaMFNaSEV7LVWx2JT_kaC4Uoyk",
    appId: "1:867280179629:web:8da4f34a533b80339ed124",
    messagingSenderId: "867280179629",
    projectId: "chatflutter-181be",
    databaseURL: "https://chatflutter-181be-default-rtdb.firebaseio.com",
    storageBucket: "chatflutter-181be.appspot.com",
    iosBundleId: 'com.expample.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyAnKsE4cLaMFNaSEV7LVWx2JT_kaC4Uoyk",
    appId: "1:867280179629:web:8da4f34a533b80339ed124",
    messagingSenderId: "867280179629",
    projectId: "chatflutter-181be",
    databaseURL: "https://chatflutter-181be-default-rtdb.firebaseio.com",
    storageBucket: "chatflutter-181be.appspot.com",
    iosBundleId: 'com.expample.chatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyAnKsE4cLaMFNaSEV7LVWx2JT_kaC4Uoyk",
    authDomain: "chatflutter-181be.firebaseapp.com",
    databaseURL: "https://chatflutter-181be-default-rtdb.firebaseio.com",
    projectId: "chatflutter-181be",
    storageBucket: "chatflutter-181be.appspot.com",
    messagingSenderId: "867280179629",
    appId: "1:867280179629:web:8da4f34a533b80339ed124"
  );
}
