// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6b-O51jqKaj7PMPtTe8wkCbHXS7xKD6Q',
    appId: '1:885386586313:web:747574010700f4fe9bc518',
    messagingSenderId: '885386586313',
    projectId: 'fir-codelad',
    authDomain: 'fir-codelad.firebaseapp.com',
    databaseURL: 'https://fir-codelad-default-rtdb.firebaseio.com',
    storageBucket: 'fir-codelad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNlCcEGnfzO-dAERTPW_zi3SvtKWavMIs',
    appId: '1:885386586313:android:d2ede6b4ac7772d59bc518',
    messagingSenderId: '885386586313',
    projectId: 'fir-codelad',
    databaseURL: 'https://fir-codelad-default-rtdb.firebaseio.com',
    storageBucket: 'fir-codelad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6CPdYHbsBy-gYWDYej4Aw3gSOu6xZ_ks',
    appId: '1:885386586313:ios:1866226477e6f8919bc518',
    messagingSenderId: '885386586313',
    projectId: 'fir-codelad',
    databaseURL: 'https://fir-codelad-default-rtdb.firebaseio.com',
    storageBucket: 'fir-codelad.appspot.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6CPdYHbsBy-gYWDYej4Aw3gSOu6xZ_ks',
    appId: '1:885386586313:ios:1866226477e6f8919bc518',
    messagingSenderId: '885386586313',
    projectId: 'fir-codelad',
    databaseURL: 'https://fir-codelad-default-rtdb.firebaseio.com',
    storageBucket: 'fir-codelad.appspot.com',
    iosBundleId: 'com.example.chatFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6b-O51jqKaj7PMPtTe8wkCbHXS7xKD6Q',
    appId: '1:885386586313:web:f4040ab67565668b9bc518',
    messagingSenderId: '885386586313',
    projectId: 'fir-codelad',
    authDomain: 'fir-codelad.firebaseapp.com',
    databaseURL: 'https://fir-codelad-default-rtdb.firebaseio.com',
    storageBucket: 'fir-codelad.appspot.com',
  );
}
